import React from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';
import SectionMark from '../../SectionMark';
import {
  Grid,
  Box,
  Card,
  CardContent,
  CardMedia,
  CardActions,
} from '@material-ui/core';
import CropOriginalIcon from '@material-ui/icons/CropOriginal';
import useStyles from './styles';
import Typography from '@components/Typography';
import Button from '../../components/ButtonStatic';
import { trimText } from '../../../utils';
import TextField from '../../TextField';
import { dummyText, dummyTextEng } from '../../../constant';

const ProductDetail = (props) => {
  const {
    tab,
    data,
    useform: { _control },
    previewMode,
    // level,
    products,
  } = props;
  const classes = useStyles();

  const maxLength = 100;

  const renderEmptyCards = () => {
    const cards = [];
    for (let i = 1; i <= 2; i++) {
      cards.push(
        <Grid item key={`ProductDetail${i}`} md={6} xs={12}>
          <Card className={clsx(classes.card, classes.emptyCard)}>
            <div className={classes.emptyImage}>
              <CropOriginalIcon className={classes.icon} />
            </div>

            <Box style={{ display: 'flex', flexDirection: 'column' }}>
              <CardContent>
                <div>
                  <Typography color="general-main" variant="h5" weight="medium">
                    Automatically Generated
                  </Typography>
                </div>
                <div>
                  <Typography color="general-main" variant="caption">
                    This card was automatically generated by product detail
                    mapping data
                  </Typography>
                </div>
              </CardContent>
            </Box>
          </Card>
        </Grid>,
      );
    }

    return cards;
  };

  const renderContentCards = (cardList) => {
    const cards = [];

    cardList.map((product, i) => {
      const description = product.description.replace(/(<([^>]+)>)/gi, '');

      cards.push(
        <Grid item key={`ProductDetail${i}`} md={6} xs={12}>
          <Card className={classes.card}>
            <CardMedia
              alt={product.title}
              component="img"
              image={product.imageUrl}
              style={{ width: '40%', height: '100%' }}
            />
            <Box style={{ display: 'flex', flexDirection: 'column' }}>
              <CardContent>
                <div>
                  <Typography color="general-main" variant="h5">
                    {product.title}
                  </Typography>
                </div>
                <div>
                  <Typography color="general-main" variant="caption">
                    {trimText(description, maxLength)}
                  </Typography>
                </div>
              </CardContent>
              <CardActions style={{ width: '100%', padding: '0 1rem 1rem' }}>
                <Button variant="ghost">Learn More</Button>
              </CardActions>
            </Box>
          </Card>
        </Grid>,
      );
    });

    return cards;
  };

  const checkCardRender = (_title) => {
    const selectedProduct = products[tab].find(({ title }) => title === _title);
    return selectedProduct?.cardList?.length > 0
      ? renderContentCards(selectedProduct.cardList)
      : renderEmptyCards();
  };

  const renderProductSection = () => {
    const sectionsId = [];
    const sectionsEn = [];

    if (tab === 'id') {
      data.id.map((field, i) => {
        sectionsId.push(
          <div
            key={field.id}
            style={{
              margin: '16px 0',
              marginBottom: i + 1 === data.id.length ? 0 : '5rem',
            }}
          >
            <Typography color="general-main" variant="h3" weight="medium">
              {field.title}
            </Typography>
            <TextField
              control={_control}
              disabled={previewMode}
              multiline
              name={`productDetailsId[${i}].description`}
              placeholder={dummyText.title}
            />
            <Grid className={classes.cardContainer} container spacing={3}>
              {checkCardRender(field.title)}
            </Grid>
          </div>,
        );
      });

      return sectionsId;
    }

    if (tab === 'en') {
      data.en.map((field, i) => {
        sectionsEn.push(
          <div key={field.id} style={{ margin: '16px 0' }}>
            <Typography color="general-main" variant="h4" weight="medium">
              {field.title}
            </Typography>
            <TextField
              control={_control}
              defaultValue={field.description}
              multiline
              name={`productDetailsEn[${i}].description`}
              placeholder={dummyTextEng.title}
            />
            <Grid className={classes.cardContainer} container spacing={3}>
              {checkCardRender(field.title)}
            </Grid>
          </div>,
        );
      });

      return sectionsEn;
    }
  };

  return (
    <div
      style={{
        border: previewMode ? 'none' : '2px dashed #E4E7E9',
        borderTop: 'none',
        position: 'relative',
      }}
    >
      {!previewMode && (
        <SectionMark
          description="This section automatically added product detail link, based on product detail mapping data"
          title="Product Detail"
        />
      )}

      <div
        style={{
          padding: previewMode ? '5rem 1rem' : '5rem 4rem',
          width: '100%',
          maxWidth: '1280px',
          marginInline: 'auto',
        }}
      >
        {renderProductSection()}
      </div>
    </div>
  );
};

ProductDetail.defaultProps = {
  data: {
    en: [],
    id: [],
  },
  level: '',
  previewMode: false,
  useform: {},
};

ProductDetail.propTypes = {
  data: PropTypes.object,
  level: PropTypes.string,
  previewMode: PropTypes.bool,
  products: PropTypes.object.isRequired,
  tab: PropTypes.string.isRequired,
  useform: PropTypes.object,
};

export default ProductDetail;
