import React from 'react';
import _ from 'lodash';
import Typography from '@components/Typography';

const labelComponent = (required, label) => (
  <>
    {required && (
      <Typography
        children="*"
        color="primary-main"
        variant="subtitle2"
        weight="bold"
      />
    )}
    {label && (
      <Typography
        children={label}
        color="general-mid"
        inline
        variant="subtitle2"
        weight="medium"
      />
    )}
  </>
);

export const tableHeader = (isAttributeAttached = false) => {
const withChildProduct = [{
  cellStyle: {
    minWidth: 180,
    width: 318,
  },
  label: labelComponent(false, 'Child'),
  name: 'childName',
  keepLabel: true,
},
{
  cellStyle: {
    minWidth: 180,
    width: 318,
  },
  label: labelComponent(false, 'Grandchild'),
  name: 'grandchildName',
  keepLabel: true,
}]

const general = [{
    cellStyle: {
      minWidth: 180,
      width: 318,
    },
    label: labelComponent(false, 'Description'),
    name: 'description',
    keepLabel: true,
  },
  {
    cellStyle: {
      minWidth: 50,
      width: 133,
    },
    label: labelComponent(false, 'Quantity'),
    name: 'qty',
    keepLabel: true,
  },
  {
    cellStyle: {
      minWidth: 180,
      width: 168,
    },
    label: labelComponent(false, 'Payment Type'),
    name: 'paymentType',
    keepLabel: true,
  },
  {
    cellStyle: {
      minWidth: 180,
      width: 174,
    },
    label: labelComponent(false, 'Total Price'),
    name: 'totalPrice',
    keepLabel: true,
    hasTooltipHeader: true,
    tooltipHeader: 'This is the price after multiplying by the quantity.',
    currency: true,
  },
];

return !isAttributeAttached ? [...withChildProduct, ...general] : general;
}

export const alertText = {
  customerInfo:
    'If you don’t have the <strong>"Billing Account and Service Account"</strong>, please contact WDM first for creating on <strong>NCX or Starclick.</strong>',
  document:
    'If you don’t have the <strong>“Master Agreement Document”</strong>, please create first on <strong>NCX.</strong>',
};

export const steps = [
  'Customer Information',
  'Sales Team',
  'Product',
  'Document',
];

const registerredField = [
  //step1
  'businessType',
  'custAccntName',
  'name',
  'jobTitle',
  'email',
  'phone',
  'billingAccount',
  'serviceAccount',

  //step2
  'accountManager',
  'segmentManager',

  //step 3
  'product',
  'orderItem',
  'mrc',
  'otc',
  'location',
  'productName',

  //step4
  'bakesNumber',
  'purchaseOrderNumber',
  'purchaseOrderDate',
  'purchaseOrderSignerName',
  'bakesStartDate',
  'bakesEndDate',
  'bakesDuration',
  'noteProgress',
  'radioBakes',
  'agreementDocument',
  'bakesFile',
  'agreementMasterNumber',
  'ttdBakesDays',
  'expectedDeliveryDate',
  'bakesNote',
];

const defaultValue = {
  accountManager: [],
  ttdBakesDays: null,
};

export const normalizeData = (data) => {
  let cleanData = {};

  if (data) {
    Object.keys(data).forEach((v) => {
      if (registerredField.includes(v)) {
        switch (v) {
          case 'agreementDocument':
            return (cleanData = { ...cleanData, [v]: data[v][0] });
          case 'bakesNumber': {
            //because it use field bakesNumberAuto
            if (data?.radioBakes === '1' || data?.isExistingBakes) {
              return cleanData;
            }
            return (cleanData = { ...cleanData, [v]: data[v] });
          }
          case 'bakesFile': {
            //because it generated by api when click submit
            if (data?.radioBakes === '1' && !data?.isHaveBakes) {
              return cleanData;
            }
            return (cleanData = { ...cleanData, [v]: data[v][0] });
          }
          case 'segmentManager': {
            if (!_.isEmpty(data[v])) {
              return (cleanData = {
                ...cleanData,
                [v]: {
                  ..._.omit(data[v], 'contactNumber'),
                  phone: data[v]?.contactNumber || data?.phone,
                },
              });
            } else return cleanData;
          }
          case 'product': {
            //there are 2 type of product, string and array
            if (typeof data[v] === 'string') {
              return (cleanData = { ...cleanData, [v]: [] });
            }
            return (cleanData = { ...cleanData, [v]: data[v] });
          }
          case 'agreementMasterNumber': {
            return (cleanData = {
              ...cleanData,
              [v]: {
                label: data[v]?.agreeNumber,
                value: data[v]?.agreeNumber,
                data: data[v],
              },
            });
          }
          default:
            if (data[v] === null) {
              return (cleanData = { ...cleanData, [v]: defaultValue[v] || '' });
            }
            return (cleanData = { ...cleanData, [v]: data[v] });
        }
      }
    });
  }

  return cleanData || null;
};
