module.exports = {
  testTimeout: 30000,
  collectCoverageFrom: [
    'src/utils/**/*.js',
    'src/components/**/*.js',
    'src/fragments/**/*.js',
    'src/containers/**/*.js',
    'src/layouts/**/*.js',
    '!**/styles.js',
    '!**/repositories.js',
    '!**/validation.js',
    '!**/mask/*.js',
    '!**/index.js',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/_DesignSystem/**/*.js',
  ],
  moduleNameMapper: {
    '^.+\\.(css|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',
    '^.+\\.(jpg|jpeg|png|gif|webp|avif|svg)$': `<rootDir>/__mocks__/fileMock.js`,
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@configs/(.*)$': '<rootDir>/src/configs/$1',
    '^@configs': '<rootDir>/src/configs/index.js',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@constants': '<rootDir>/src/constants/index.js',
    '^@containers/(.*)$': '<rootDir>/src/containers/$1',
    '^@context/(.*)$': '<rootDir>/src/context/$1',
    '^@firebaseConfig/(.*)$': '<rootDir>/src/firebase/$1',
    '^@fragments/(.*)$': '<rootDir>/src/fragments/$1',
    '^@layouts/(.*)$': '<rootDir>/src/layouts/$1',
    '^@reducers': '<rootDir>/src/reducers/index.js',
    '^@reducers/(.*)$': '<rootDir>/src/reducers/$1',
    '^@styles/(.*)$': '<rootDir>/src/styles/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@__old/(.*)$': '<rootDir>/src/__old/$1',
    // "^yourPath/(.*)": "<rootDir>\\yourPath\\$1"
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js', 'jest-canvas-mock'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
  },
  transformIgnorePatterns: [
    // '/node_modules/',
    `/node_modules/(?!(${['react-pdf', 'crypsi.js'].join('|')})/)`,
    '^.+\\.module\\.(css|sass|scss)$',
  ],
};
