const actions = {
  LOADING: 'LOADING',
  DONE_LOADING: 'DONE_LOADING',
  LOADING_SUBMIT: 'LOADING_SUBMIT',
  DONE_LOADING_SUBMIT: 'DONE_LOADING_SUBMIT',
  LOADING_LAZY: 'LOADING_LAZY',
  DONE_LOADING_LAZY: 'DONE_LOADING_LAZY',
  LOADING_NOTIFICATION: 'LOADING_NOTIFICATION',
  DONE_LOADING_NOTIFICATION: 'DONE_LOADING_NOTIFICATION',
  LOADING_TABLE: 'LOADING_TABLE',
  DONE_LOADING_TABLE: 'DONE_LOADING_TABLE',

  TRANSLATE_ID_EN: 'TRANSLATE_ID_EN',

  POPUP_ALERT: 'POPUP_ALERT',

  SEARCH_QUERY: 'SEARCH_QUERY',

  LOGIN_FAILED: 'LOGIN_FAILED',
  FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED',

  LIST_SERVICE_ASSURANCE: 'LIST_SERVICE_ASSURANCE',
  DETAIL_SERVICE_ASSURANCE: 'DETAIL_SERVICE_ASSURANCE',
  SET_ACTIVE_TAB_ASSURANCE: 'SET_ACTIVE_TAB_ASSURANCE',

  LIST_SERVICE_ASSURANCE_NEUCLOUD: 'LIST_SERVICE_ASSURANCE_NEUCLOUD',
  DETAIL_SERVICE_ASSURANCE_NEUCLOUD: 'DETAIL_SERVICE_ASSURANCE_NEUCLOUD',

  LIST_KEYWORD: 'LIST_KEYWORD',
  DETAIL_KEYWORD: 'DETAIL_KEYWORD',

  LIST_LINK: 'LIST_LINK',
  DETAIL_LINK: 'DETAIL_LINK',

  LIST_UMB: 'LIST_UMB',
  DETAIL_UMB: 'DETAIL_UMB',

  LIST_LBA: 'LIST_LBA',
  DETAIL_LBA: 'DETAIL_LBA',
  APPROVAL_LBA: 'APPROVAL_LBA',
  GRAPH_LBA: 'GRAPH_LBA',

  LIST_SENDER_ID: 'LIST_SENDER_ID',
  DETAIL_SENDER_ID: 'DETAIL_SENDER_ID',
  UPDATE_DETAIL_SENDER_ID: 'UPDATE_DETAIL_SENDER_ID',
  GRAPH_SENDER_ID: 'GRAPH_SENDER_ID',

  NOTIFICATION: 'NOTIFICATION',

  DETAIL_PURCHASE_ORDER: 'DETAIL_PURCHASE_ORDER',
  LIST_PURCHASE_ORDER: 'LIST_PURCHASE_ORDER',
  LIST_PO_PRODUCT: 'LIST_PO_PRODUCT',
  LIST_PO_CUSTOMER: 'LIST_PO_CUSTOMER',

  LIST_MODIFICATION_ORDER: 'LIST_MODIFICATION_ORDER',
  DETAIL_MODIFICATION_ORDER: 'DETAIL_MODIFICATION_ORDER',
  LIST_MO_CUSTOMER: 'LIST_MO_CUSTOMER',
  LIST_BAKES_MO: 'LIST_BAKES_MO',
  SET_SERVER_STATUS: 'SET_SERVER_STATUS',

  LIST_BASO: 'LIST_BASO',
  DETAIL_BASO: 'DETAIL_BASO',
  LIST_BASO_PRODUCT: 'LIST_BASO_PRODUCT',
  LIST_BASO_CUSTOMER: 'LIST_BASO_CUSTOMER',
  LIST_BASO_AM: 'LIST_BASO_AM',
  LIST_BASO_SEGMENT: 'LIST_BASO_SEGMENT',

  LIST_QUOTATION: 'LIST_QUOTATION',
  DETAIL_QUOTATION: 'DETAIL_QUOTATION',
  QUOTATION_CREATE_DATA: 'QUOTATION_CREATE_DATA',
  QUOTATION_SERVICE_SPESIFICATION: 'QUOTATION_SERVICE_SPESIFICATION',

  LIST_BAKES: 'LIST_BAKES',
  DETAIL_BAKES: 'DETAIL_BAKES',
  BAKES_CREATE_DATA: 'BAKES_CREATE_DATA',

  LIST_AM_MAPPING_CUSTOMER: 'LIST_AM_MAPPING_CUSTOMER',
  LIST_AM_MAPPING_PROFILE: 'LIST_AM_MAPPING_PROFILE',

  AM_PROFILE: 'AM_PROFILE',
  AM_LIST_CUSTOMER: 'AM_LIST_CUSTOMER',
  GET_AM_MAPPING_BY_ID: 'GET_AM_MAPPING_BY_ID',

  INTERESTED_GRAPH_AM: 'INTERESTED_GRAPH_AM',
  INTERESTED_GRAPH_PRODUCT: 'INTERESTED_GRAPH_PRODUCT',
  INTERESTED_GRAPH_SEGMENT: 'INTERESTED_GRAPH_SEGMENT',
  INTERESTED_GRAPH_STATUS: 'INTERESTED_GRAPH_STATUS',
  INTERESTED_LIST_DETAIL: 'INTERESTED_LIST_DETAIL',
  LIST_SOURCE: 'LIST_SOURCE',
  LIST_PRODUCT: 'LIST_PRODUCT',
  LIST_AM_VALID: 'LIST_AM_VALID',
  LIST_SEGMENT_VALID: 'LIST_SEGMENT_VALID',

  PRODUCT_MANAGEMENT_SECTION: 'PRODUCT_MANAGEMENT_SECTION',
  PRODUCT_MANAGEMENT_MEDIA: 'PRODUCT_MANAGEMENT_MEDIA',
  PRODUCT_MANAGEMENT_ADD_SECTION: 'PRODUCT_MANAGEMENT_ADD_SECTION',
  PRODUCT_MANAGEMENT_ADD: 'PRODUCT_MANAGEMENT_ADD',
  PRODUCT_MANAGEMENT_CATEGORY: 'PRODUCT_MANAGEMENT_CATEGORY',
  PRODUCT_MANAGEMENT_CATEGORY1: 'PRODUCT_MANAGEMENT_CATEGORY1',
  PRODUCT_MANAGEMENT_CATEGORY2: 'PRODUCT_MANAGEMENT_CATEGORY2',
  PRODUCT_MANAGEMENT_PAGE_VALID: 'PRODUCT_MANAGEMENT_PAGE_VALID',
  PRODUCT_TRANSLATE_LANGUAGE: 'PRODUCT_TRANSLATE_LANGUAGE',
  PRODUCT_BASE_LANGUAGE: 'PRODUCT_BASE_LANGUAGE',
  PRODUCT_LOCALIZATIONS: 'PRODUCT_LOCALIZATIONS',
  PRODUCT_ACTIVE_TAB: 'PRODUCT_ACTIVE_TAB',
  PRODUCT_LIST_LANGUAGE: 'PRODUCT_LIST_LANGUAGE',
  RESET: 'RESET',

  LIST_ACTIVATE_CUSTOMER: 'LIST_ACTIVATE_CUSTOMER',
  LIST_OPERATOR_TYPE: 'LIST_OPERATOR_TYPE',
  LIST_CUSTOMER_SMSC: 'LIST_CUSTOMER_SMSC',
  LIST_CUSTOMER_GP: 'LIST_CUSTOMER_GP',

  OTP_COUNTER: 'OTP_COUNTER',
  SITE_VISIT_DETAIL: 'SITE_VISIT_DETAIL',

  GRAPH_SMSC: 'GRAPH_SMSC',

  USER_MANAGEMENT_DETAIL: 'USER_MANAGEMENT_DETAIL',
  LIST_COMPANY_PROFILE: 'LIST_COMPANY_PROFILE',
  LIST_ROLE_USER: 'LIST_ROLE_USER',
  USER_MANAGEMENT_LIST_PRIVILEGE: 'USER_MANAGEMENT_LIST_PRIVILEGE',
  USER_PROFILE: 'USER_PROFILE',
  USER_MANAGEMENT_COUNTRY: 'USER_MANAGEMENT_COUNTRY',
  LIST_PRIVILEGE_BY_USER_ID: 'LIST_PRIVILEGE_BY_USER_ID',
  USER_MANAGEMENT_RESET: 'USER_MANAGEMENT_RESET',
  LIST_DETAIL_PRIVILEGE: 'LIST_DETAIL_PRIVILEGE',

  APPROVAL_MRTG_CUSTOMER: 'APPROVAL_MRTG_CUSTOMER',
  APPROVAL_MRTG_CUSTOMER_DETAIL: 'APPROVAL_MRTG_CUSTOMER_DETAIL',
  APPROVAL_MRTG_LOGIN_DATA_DETAIL: 'APPROVAL_MRTG_LOGIN_DATA_DETAIL',
  APPROVAL_MRTG_LOGIN_DATA_DETAIL_ADD: 'APPROVAL_MRTG_LOGIN_DATA_DETAIL_ADD',
  APPROVAL_MRTG_CUSTOMER_DETAIL_UPDATE: 'APPROVAL_MRTG_CUSTOMER_DETAIL_UPDATE',
  APPROVAL_MRTG_REQUEST: 'APPROVAL_MRTG_REQUEST',
  APPROVAL_MRTG_REQUEST_DETAIL: 'APPROVAL_MRTG_REQUEST_DETAIL',
  APPROVAL_MRTG_REQUEST_DETAIL_UPDATE: 'APPROVAL_MRTG_REQUEST_DETAIL_UPDATE',
  APPROVAL_MRTG_SERVICE: 'APPROVAL_MRTG_SERVICE',

  DETAIL_INVOICE: 'DETAIL_INVOICE',
  DETAIL_INVOICE_CLAIM: 'DETAIL_INVOICE_CLAIM',
  LIST_NOTIFICATION_MANAGEMENT: 'LIST_NOTIFICATION_MANAGEMENT',
  DETAIL_COMPANY_NOTIFICATION_MANAGEMENT:
    'DETAIL_COMPANY_NOTIFICATION_MANAGEMENT',
  DETAIL_COMPANY_NOTIFICATION_MANAGEMENT_UPDATE:
    'DETAIL_COMPANY_NOTIFICATION_MANAGEMENT_UPDATE',
  LIST_INVOICE_NOTIFICATION_MANAGEMENT: 'LIST_INVOICE_NOTIFICATION_MANAGEMENT',

  ROLE_DETAIL: 'ROLE_DETAIL',
  LIST_PRIVILEGE: 'LIST_PRIVILEGE',

  DETAIL_PRIVILEGES: 'DETAIL_PRIVILEGES',
  EDIT_PRIVILEGES: 'EDIT_PRIVILEGES',
  VALID_FUNCTION_PRIVILEGES: 'VALID_FUNCTION_PRIVILEGES',
  VALID_FUNCTION_ALIAS_PRIVILEGES: 'VALID_FUNCTION_ALIAS_PRIVILEGES',
  VALID_DESCRIPTION_PRIVILEGES: 'VALID_DESCRIPTION_PRIVILEGES',
  VALID_CATEGORY_PRIVILEGES: 'VALID_CATEGORY_PRIVILEGES',
  VALID_FEATURE_PRIVILEGES: 'VALID_FEATURE_PRIVILEGES',
  VALID_ISEMPTY_PRIVILEGES: 'VALID_ISEMPTY_PRIVILEGES',
  VALID_ISPRIVILEGES_USED: 'VALID_ISPRIVILEGES_USED',
};

export default actions;
