import { capitalize } from '@utils/text';

export const pickMessageFollowUp = (type, variant) => {
  if (!type) {
    return undefined;
  }

  const confirmMessage = {
    add: `Are you sure want to add this new ${type}?`,
    edit: `Are you sure want to edit this ${type}?`,
  }[variant];

  const successMessage = {
    add: `New ${type} successfully added`,
    edit: `${capitalize(type || '')} was successfully edited`,
  }[variant];

  return {
    confirmMessage,
    successMessage,
  };
};

export const pickOptionType = (status) => {
  switch (status) {
    case 'Valid':
    case 'Qualify':
    case 'Delay Opportunity':
      return [
        { label: 'Administration', value: 'Administration' },
        { label: 'Adverse Event', value: 'Adverse Event' },
        { label: 'Alert', value: 'Alert' },
        { label: 'Analyst', value: 'Analyst' },
        { label: 'Appeal Request', value: 'Appeal Request' },
        { label: 'Appointment', value: 'Appointment' },
        { label: 'Arrest', value: 'Arrest' },
        { label: 'Assessment', value: 'Assessment' },
        {
          label: 'Authorization Notification',
          value: 'Authorization Notification',
        },
        { label: 'Authorization Request', value: 'Authorization Request' },
        { label: 'Best Actions', value: 'Best Actions' },
        { label: 'Birthday Call', value: 'Birthday Call' },
        { label: 'Build Display', value: 'Build Display' },
        { label: 'Call', value: 'Call' },
        { label: 'Call - Callback', value: 'Call - Callback' },
        { label: 'Call - Inbound', value: 'Call - Inbound' },
        { label: 'Call Me Now', value: 'Call Me Now' },
        { label: 'Call - Outbound', value: 'Call - Outbound' },
        { label: 'Call - Voice Mail', value: 'Call - Voice Mail' },
        { label: 'Call - Web Callback', value: 'Call - Web Callback' },
        { label: 'Campaign Launch', value: 'Campaign Launch' },
        { label: 'Campaign Load', value: 'Campaign Load' },
        { label: 'Change Order', value: 'Change Order' },
        { label: 'Chat - Inbound', value: 'Chat - Inbound' },
        { label: 'Chat - Transfer', value: 'Chat - Transfer' },
        { label: 'Collect Payment', value: 'Collect Payment' },
        { label: 'Contact Behavior', value: 'Contact Behavior' },
        { label: 'Contract-Amendment', value: 'Contract-Amendment' },
        { label: 'Contract-Revision', value: 'Contract-Revision' },
        { label: 'Conviction', value: 'Conviction' },
        { label: 'Correspondence', value: 'Correspondence' },
        { label: 'Court', value: 'Court' },
        { label: 'Crime', value: 'Crime' },
        { label: 'Current Customer', value: 'Current Customer' },
        { label: 'Current Partner', value: 'Current Partner' },
        { label: 'Dealership Visit', value: 'Dealership Visit' },
        { label: 'Delivery', value: 'Delivery' },
        { label: 'Demonstration', value: 'Demonstration' },
        { label: 'Depot Repair', value: 'Depot Repair' },
        { label: 'Diagnosis', value: 'Diagnosis' },
        { label: 'Document', value: 'Document' },
        { label: 'Email', value: 'Email' },
        { label: 'Email - Inbound', value: 'Email - Inbound' },
        { label: 'Email - Outbound', value: 'Email - Outbound' },
        { label: 'Event', value: 'Event' },
        { label: 'Export', value: 'Export' },
        { label: 'Fax', value: 'Fax' },
        { label: 'Fax - Inbound', value: 'Fax - Inbound' },
        { label: 'Fax - Outbound', value: 'Fax - Outbound' },
        { label: 'Field Appraisal', value: 'Field Appraisal' },
        { label: 'Field Repair', value: 'Field Repair' },
        {
          label: 'Field Service Assignment',
          value: 'Field Service Assignment',
        },
        { label: 'Follow-Up', value: 'Follow-Up' },
        { label: 'Fraud-Action', value: 'Fraud-Action' },
        { label: 'Fresh Uo', value: 'Fresh Uo' },
        { label: 'FYI', value: 'FYI' },
        { label: 'Generate Campaign Lists', value: 'Generate Campaign Lists' },
        { label: 'Get BASO', value: 'Get BASO' },
        { label: 'Get Billing Approval', value: 'Get Billing Approval' },
        { label: 'Import', value: 'Import' },
        { label: 'Incident', value: 'Incident' },
        { label: 'Information Needed', value: 'Information Needed' },
        { label: 'InQuira Answer', value: 'InQuira Answer' },
        { label: 'Installation', value: 'Installation' },
        { label: 'In Store Activity', value: 'In Store Activity' },
        { label: 'In Store Visit', value: 'In Store Visit' },
        { label: 'Internal', value: 'Internal' },
        { label: 'Internet Lead', value: 'Internet Lead' },
        { label: 'Investigation', value: 'Investigation' },
        { label: 'Investment NA', value: 'Investment NA' },
        { label: 'Letter - Inbound', value: 'Letter - Inbound' },
        { label: 'Letter - Outbound', value: 'Letter - Outbound' },
        { label: 'Literature Distribution', value: 'Literature Distribution' },
        { label: 'Maintenance', value: 'Maintenance' },
        { label: 'Manager Review', value: 'Manager Review' },
        { label: 'Marketing eEvent', value: 'Marketing eEvent' },
        { label: 'Marketing Program', value: 'Marketing Program' },
        {
          label: 'Medical Information Request',
          value: 'Medical Information Request',
        },
        { label: 'Meeting', value: 'Meeting' },
        { label: 'Member Benefit Inquiry', value: 'Member Benefit Inquiry' },
        {
          label: 'Member Eligibility Inquiry',
          value: 'Member Eligibility Inquiry',
        },
        { label: 'Merchandising Audit', value: 'Merchandising Audit' },
        { label: 'Milestone', value: 'Milestone' },
        { label: 'No - Activity', value: 'No - Activity' },
        { label: 'Notes', value: 'Notes' },
        { label: 'Other', value: 'Other' },
        { label: 'Other Member Question', value: 'Other Member Question' },
        { label: 'Paging', value: 'Paging' },
        { label: 'Panel Update', value: 'Panel Update' },
        { label: 'Payment Inquiry', value: 'Payment Inquiry' },
        { label: 'Personal', value: 'Personal' },
        { label: 'Place POS Material', value: 'Place POS Material' },
        { label: 'Possible Actions', value: 'Possible Actions' },
        { label: 'Preparation', value: 'Preparation' },
        { label: 'Presentation', value: 'Presentation' },
        { label: 'Rebate', value: 'Rebate' },
        { label: 'Recommended Activity', value: 'Recommended Activity' },
        { label: 'Recruiting', value: 'Recruiting' },
        { label: 'Reference - Call', value: 'Reference - Call' },
        { label: 'Reference - Testimonial', value: 'Reference - Testimonial' },
        { label: 'Reference - Visit', value: 'Reference - Visit' },
        { label: 'Referral Notification', value: 'Referral Notification' },
        { label: 'Referral Request', value: 'Referral Request' },
        { label: 'Rep Approval Request', value: 'Rep Approval Request' },
        {
          label: 'Request for Repossession',
          value: 'Request for Repossession',
        },
        { label: 'Research', value: 'Research' },
        { label: 'Reservation', value: 'Reservation' },
        { label: 'Reset', value: 'Reset' },
        { label: 'Resolution', value: 'Resolution' },
        { label: 'Retail Assessment', value: 'Retail Assessment' },
        { label: 'Retail Audit', value: 'Retail Audit' },
        { label: 'Retail Order', value: 'Retail Order' },
        { label: 'Return Order', value: 'Return Order' },
        { label: 'Review Billings', value: 'Review Billings' },
        { label: 'Sales Step', value: 'Sales Step' },
        { label: 'Samples Request', value: 'Samples Request' },
        {
          label: 'Schedule An Office Visit',
          value: 'Schedule An Office Visit',
        },
        { label: 'Security Alert', value: 'Security Alert' },
        { label: 'Sell Notes', value: 'Sell Notes' },
        { label: 'Send Pkg to Rep Agency', value: 'Send Pkg to Rep Agency' },
        { label: 'Session', value: 'Session' },
        { label: 'Siebel Calendar', value: 'Siebel Calendar' },
        { label: 'Siebel Task', value: 'Siebel Task' },
        {
          label: 'Special Business Request',
          value: 'Special Business Request',
        },
        { label: 'Stage Execution', value: 'Stage Execution' },
        { label: 'Stock Transfer', value: 'Stock Transfer' },
        { label: 'Store Check', value: 'Store Check' },
        { label: 'Surveillance', value: 'Surveillance' },
        { label: 'Tactic', value: 'Tactic' },
        { label: 'Targeted Call', value: 'Targeted Call' },
        {
          label: 'Technical Support Follow-Up',
          value: 'Technical Support Follow-Up',
        },
        { label: 'Telephone', value: 'Telephone' },
        { label: 'Test Drive', value: 'Test Drive' },
        { label: 'Text Chat', value: 'Text Chat' },
        { label: 'To Do', value: 'To Do' },
        { label: 'Training Class', value: 'Training Class' },
        { label: 'Upgrade', value: 'Upgrade' },
        { label: 'Vehicle Delivery', value: 'Vehicle Delivery' },
        { label: 'Vehicle Prep', value: 'Vehicle Prep' },
        { label: 'Vendor', value: 'Vendor' },
        { label: 'Visiting Activity', value: 'Visiting Activity' },
        { label: 'Voice Over IP', value: 'Voice Over IP' },
        { label: 'Warranty Service', value: 'Warranty Service' },
        { label: 'Web - Inbound', value: 'Web - Inbound' },
        { label: 'Web Update', value: 'Web Update' },
        { label: 'Wireless Message', value: 'Wireless Message' },
        {
          label: 'Check feasibility to network',
          value: 'Check feasibility to network',
        },
        { label: 'Site Survey', value: 'Site Survey' },
      ];
    default:
      return [
        {
          label: 'Check feasibility to network',
          value: 'Check feasibility to network',
        },
        {
          label: 'Identity customer requirement',
          value: 'Identity customer requirement',
        },
      ];
  }
};

export const pickOptionStatus = (status) => {
  switch (status) {
    case 'valid':
    case 'qualify':
    case 'Delay Opportunity':
      return [
        { label: 'Acknowledged', value: 'Acknowledged' },
        { label: 'Active', value: 'Active' },
        { label: 'Alerted', value: 'Alerted' },
        { label: 'Approved', value: 'Approved' },
        { label: 'Planned', value: 'Planned' },
        { label: 'Auto Responded', value: 'Auto Responded' },
        // { label: 'Cancelled', value: 'Cancelled' },
        { label: 'Declined', value: 'Declined' },
        { label: 'Delivery Failed', value: 'Delivery Failed' },
        { label: 'Dispatch Failed', value: 'Dispatch Failed' },
        { label: 'Submitted', value: 'Submitted' },
        { label: 'Dispatched', value: 'Dispatched' },
        { label: 'Done', value: 'Done' },
        { label: 'Synchronized', value: 'Synchronized' },
        { label: 'In Progress', value: 'In Progress' },
        { label: 'Not Acknowledged', value: 'Not Acknowledged' },
        { label: 'Auto-Created', value: 'Auto-Created' },
        { label: 'Not Started', value: 'Not Started' },
        { label: 'On Hold', value: 'On Hold' },
        { label: 'Auto-Updated', value: 'Auto-Updated' },
        { label: 'Queued', value: 'Queued' },
        { label: 'Booked', value: 'Booked' },
        { label: 'Requested', value: 'Requested' },
        { label: 'Rescheduled - Customer', value: 'Rescheduled - Customer' },
        { label: 'Rescheduled - Rep', value: 'Rescheduled - Rep' },
        { label: 'Double Booked', value: 'Double Booked' },
        { label: 'Scheduled', value: 'Scheduled' },
        { label: 'Sent', value: 'Sent' },
        { label: 'To Be Deleted', value: 'To Be Deleted' },
        { label: 'Preparing Documents', value: 'Preparing Documents' },
        { label: 'Unassigned', value: 'Unassigned' },
        { label: 'V Unscheduled', value: 'V Unscheduled' },
        { label: 'Quoted', value: 'Quoted' },
        { label: 'En Route', value: 'En Route' },
        { label: 'Re-rent', value: 'Re-rent' },
        { label: 'Signed', value: 'Signed' },
        { label: 'Transferred', value: 'Transferred' },
        { label: 'Signed and Synchronized', value: 'Signed and Synchronized' },
        { label: 'Withdrawn', value: 'Withdrawn' },
        { label: 'Locked', value: 'Locked' },
        { label: 'Submitted for Approval', value: 'Submitted for Approval' },
        { label: 'Draft', value: 'Draft' },
        { label: 'Approval in Process', value: 'Approval in Process' },
        { label: 'Sanction', value: 'Sanction' },
        { label: 'Open', value: 'Open' },
        { label: 'Closed', value: 'Closed' },
        { label: 'Completed', value: 'Completed' },
        { label: 'Invalid', value: 'Invalid' },
        { label: 'Confirmed', value: 'Confirmed' },
        { label: 'Attended', value: 'Attended' },
        { label: 'Not Attended', value: 'Not Attended' },
        { label: 'Partial', value: 'Partial' },
        { label: 'Failed', value: 'Failed' },
        { label: 'Success', value: 'Success' },
      ];
    default:
      return [
        { label: 'Done', value: 'Done' },
        { label: 'In Progress', value: 'In Progress' },
        { label: 'Open', value: 'Open' },
        // { label: 'Cancelled', value: 'Cancelled' },
        // { label: 'Skipped', value: 'Skipped' },
      ];
  }
};
