import React from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';
import {
  Grid,
  Card,
  CardActions,
  CardContent,
  CardMedia,
} from '@material-ui/core';
import CropOriginalIcon from '@material-ui/icons/CropOriginal';
import Typography from '@components/Typography';
import Button from '../../components/ButtonStatic';
import SectionMark from '../../SectionMark';
import TextField from '../../components/TextFieldContent';
import { dummyText, dummyTextEng } from '../../../constant';
import { trimText } from '../../../utils';
import useActions from './hooks/useActions';
import useStyles from './styles';

const ProductAndServices = (props) => {
  const { data, tab, level, previewMode } = props;
  const { _control } = useActions(props);
  const classes = useStyles(previewMode);

  const maxLength = 100;

  const renderEmptyCards = () => {
    const cards = [];

    for (let i = 1; i <= 3; i++) {
      cards.push(
        <Grid item sm={4} xs={12}>
          <Card className={clsx(classes.card, classes.emptyCard)}>
            <div className={classes.w100}>
              <div className={classes.emptyImage}>
                <CropOriginalIcon className={classes.icon} />
              </div>
              <CardContent className={classes.pb0}>
                <div>
                  <Typography color="general-main" variant="h5" weight="medium">
                    Automatically Generated
                  </Typography>
                </div>
                <div>
                  <Typography color="general-main" variant="subtitle2">
                    This card was automatically generated by L1 mapping data
                  </Typography>
                </div>
              </CardContent>
            </div>
          </Card>
        </Grid>,
      );
    }

    return cards;
  };

  const renderContentCards = () => {
    const cards = [];

    data[tab].map((data, i) => {
      cards.push(
        <Grid item key={`Product&Services${i}`} sm={4} xs={12}>
          <Card className={classes.card}>
            <div className={classes.w100}>
              <CardMedia
                alt={data.name}
                className={classes.cardImage}
                component="img"
                height="176"
                image={data.imageUrl}
              />
              <CardContent className={classes.pb0}>
                <div>
                  <Typography color="general-main" variant="h5" weight="medium">
                    {data.title}
                  </Typography>
                </div>
                <div>
                  <Typography color="general-main" variant="subtitle2">
                    {trimText(
                      data.description.replace(/(<([^>]+)>)/gi, ''),
                      maxLength,
                    )}
                  </Typography>
                </div>
              </CardContent>
            </div>

            <CardActions className={classes.cardActions}>
              <Button>LEARN MORE</Button>
            </CardActions>
          </Card>
        </Grid>,
      );
    });

    return cards;
  };

  const checkCardRender = () => {
    if (tab === 'id') {
      return data.id.length > 0 ? renderContentCards() : renderEmptyCards();
    } else {
      return data.en.length > 0 ? renderContentCards() : renderEmptyCards();
    }
  };

  return (
    <div className={classes.root}>
      {!previewMode && (
        <SectionMark
          description="This section automatically added product & services link, based on L1 mapping data"
          title="Product & Services"
        />
      )}

      <div className={classes.content}>
        <TextField
          control={_control}
          disabled={previewMode}
          fontSize="2.25rem"
          multiline={true}
          name={`${level}ProductServicesTitle${tab}`}
          noSpacing
          placeholder={tab === 'id' ? dummyText.title : dummyTextEng.title}
          position="center"
          weight="bold"
        />

        <Grid className={classes.cardContainer} container spacing={3}>
          {checkCardRender()}
        </Grid>
      </div>
    </div>
  );
};

ProductAndServices.defaultProps = {
  data: { id: [], en: [] },
  previewMode: false,
  useform: {},
};

ProductAndServices.propTypes = {
  data: PropTypes.object,
  level: PropTypes.string.isRequired,
  previewMode: PropTypes.bool,
  tab: PropTypes.string.isRequired,
  useform: PropTypes.object,
};

export default ProductAndServices;
